        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 22 01:04:27 2021
        MODULE ASSEMBAFRAME__genmod
          INTERFACE 
            SUBROUTINE ASSEMBAFRAME
            END SUBROUTINE ASSEMBAFRAME
          END INTERFACE 
        END MODULE ASSEMBAFRAME__genmod
