        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 22 01:04:27 2021
        MODULE ASSEMBATRUSS__genmod
          INTERFACE 
            SUBROUTINE ASSEMBATRUSS
            END SUBROUTINE ASSEMBATRUSS
          END INTERFACE 
        END MODULE ASSEMBATRUSS__genmod
