        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 22 01:04:27 2021
        MODULE ASSEMBA_CST__genmod
          INTERFACE 
            SUBROUTINE ASSEMBA_CST
            END SUBROUTINE ASSEMBA_CST
          END INTERFACE 
        END MODULE ASSEMBA_CST__genmod
