        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 22 01:04:27 2021
        MODULE ASSEMBB_FRAME__genmod
          INTERFACE 
            SUBROUTINE ASSEMBB_FRAME
            END SUBROUTINE ASSEMBB_FRAME
          END INTERFACE 
        END MODULE ASSEMBB_FRAME__genmod
