        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 22 01:04:27 2021
        MODULE DATA_DYM_TRUSS__genmod
          INTERFACE 
            SUBROUTINE DATA_DYM_TRUSS
            END SUBROUTINE DATA_DYM_TRUSS
          END INTERFACE 
        END MODULE DATA_DYM_TRUSS__genmod
