        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 22 01:04:27 2021
        MODULE GREDUC_CST__genmod
          INTERFACE 
            SUBROUTINE GREDUC_CST
            END SUBROUTINE GREDUC_CST
          END INTERFACE 
        END MODULE GREDUC_CST__genmod
