        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 22 01:04:27 2021
        MODULE LOADFRAME__genmod
          INTERFACE 
            SUBROUTINE LOADFRAME
            END SUBROUTINE LOADFRAME
          END INTERFACE 
        END MODULE LOADFRAME__genmod
