        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 22 01:04:27 2021
        MODULE LOADA_FRAME__genmod
          INTERFACE 
            SUBROUTINE LOADA_FRAME
            END SUBROUTINE LOADA_FRAME
          END INTERFACE 
        END MODULE LOADA_FRAME__genmod
