        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 22 01:04:27 2021
        MODULE MASSASFRAME__genmod
          INTERFACE 
            SUBROUTINE MASSASFRAME
            END SUBROUTINE MASSASFRAME
          END INTERFACE 
        END MODULE MASSASFRAME__genmod
