        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 22 01:04:27 2021
        MODULE RESOLVE_FRAME__genmod
          INTERFACE 
            SUBROUTINE RESOLVE_FRAME
            END SUBROUTINE RESOLVE_FRAME
          END INTERFACE 
        END MODULE RESOLVE_FRAME__genmod
