        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 22 01:04:27 2021
        MODULE RESOLVE__genmod
          INTERFACE 
            SUBROUTINE RESOLVE
            END SUBROUTINE RESOLVE
          END INTERFACE 
        END MODULE RESOLVE__genmod
