        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 22 01:04:27 2021
        MODULE STIFF_2D__genmod
          INTERFACE 
            SUBROUTINE STIFF_2D
            END SUBROUTINE STIFF_2D
          END INTERFACE 
        END MODULE STIFF_2D__genmod
