        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 22 01:04:27 2021
        MODULE STIFF_FRAME__genmod
          INTERFACE 
            SUBROUTINE STIFF_FRAME
            END SUBROUTINE STIFF_FRAME
          END INTERFACE 
        END MODULE STIFF_FRAME__genmod
