        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 22 01:04:27 2021
        MODULE ASSEMBB_CST__genmod
          INTERFACE 
            SUBROUTINE ASSEMBB_CST
            END SUBROUTINE ASSEMBB_CST
          END INTERFACE 
        END MODULE ASSEMBB_CST__genmod
