        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 22 01:04:27 2021
        MODULE ASSEMBA_FRAME__genmod
          INTERFACE 
            SUBROUTINE ASSEMBA_FRAME
            END SUBROUTINE ASSEMBA_FRAME
          END INTERFACE 
        END MODULE ASSEMBA_FRAME__genmod
