        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 22 01:04:27 2021
        MODULE DATA_CST__genmod
          INTERFACE 
            SUBROUTINE DATA_CST
            END SUBROUTINE DATA_CST
          END INTERFACE 
        END MODULE DATA_CST__genmod
