        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 22 01:04:27 2021
        MODULE DATA_DYM_FRAME__genmod
          INTERFACE 
            SUBROUTINE DATA_DYM_FRAME
            END SUBROUTINE DATA_DYM_FRAME
          END INTERFACE 
        END MODULE DATA_DYM_FRAME__genmod
