        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 22 01:04:27 2021
        MODULE GREDUC_FRAME__genmod
          INTERFACE 
            SUBROUTINE GREDUC_FRAME
            END SUBROUTINE GREDUC_FRAME
          END INTERFACE 
        END MODULE GREDUC_FRAME__genmod
