        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 22 01:04:27 2021
        MODULE LOADTRUSS__genmod
          INTERFACE 
            SUBROUTINE LOADTRUSS
            END SUBROUTINE LOADTRUSS
          END INTERFACE 
        END MODULE LOADTRUSS__genmod
