        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 22 01:04:27 2021
        MODULE MASSTRUSS__genmod
          INTERFACE 
            SUBROUTINE MASSTRUSS
            END SUBROUTINE MASSTRUSS
          END INTERFACE 
        END MODULE MASSTRUSS__genmod
