        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 22 01:04:27 2021
        MODULE MASSASTRUSS__genmod
          INTERFACE 
            SUBROUTINE MASSASTRUSS
            END SUBROUTINE MASSASTRUSS
          END INTERFACE 
        END MODULE MASSASTRUSS__genmod
