        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 22 01:04:27 2021
        MODULE MASSFRAME__genmod
          INTERFACE 
            SUBROUTINE MASSFRAME
            END SUBROUTINE MASSFRAME
          END INTERFACE 
        END MODULE MASSFRAME__genmod
