        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 22 01:04:27 2021
        MODULE PARAMETERSTRUSS__genmod
          INTERFACE 
            SUBROUTINE PARAMETERSTRUSS
            END SUBROUTINE PARAMETERSTRUSS
          END INTERFACE 
        END MODULE PARAMETERSTRUSS__genmod
