        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 22 01:04:27 2021
        MODULE RESOLVE_CST__genmod
          INTERFACE 
            SUBROUTINE RESOLVE_CST
            END SUBROUTINE RESOLVE_CST
          END INTERFACE 
        END MODULE RESOLVE_CST__genmod
