        !COMPILER-GENERATED INTERFACE MODULE: Mon Feb 22 01:04:27 2021
        MODULE STIFF_CST__genmod
          INTERFACE 
            SUBROUTINE STIFF_CST
            END SUBROUTINE STIFF_CST
          END INTERFACE 
        END MODULE STIFF_CST__genmod
